[package]
name = "embedded-hal-can"
version = "0.1.0"
authors = ["Ze'ev Klapow <zklapow@gmail.com>"]
repository = "https://github.com/zklapow/embedded-hal-can"
edition = "2018"

[dependencies]
nb = "0.1.2"
